# Generated by Django 5.0.6 on 2024-05-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submission_deadline', models.DateTimeField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_file', models.FileField(blank=True, upload_to='uploads/')),
                ('thumbnail', models.FileField(blank=True, upload_to='uploads/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.compo')),
            ],
        ),
        migrations.AddField(
            model_name='compo',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AlterUniqueTogether(
            name='compo',
            unique_together={('title', 'party')},
        ),
    ]
