# Generated by Django 5.0.6 on 2024-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.CharField(default='N/A', max_length=80),
            preserve_default=False,
        ),
    ]
