# Generated by Django 5.0.6 on 2024-05-19 11:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_rename_author_entry_owner_entry_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='submission_deadline',
        ),
        migrations.AddField(
            model_name='compo',
            name='metadata_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 11, 54, 55, 719048, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compo',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 11, 55, 1, 70397, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
