# Generated by Django 5.0.6 on 2024-05-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_alter_entry_options_entry_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['order'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
    ]
