# Generated by Django 5.0.6 on 2024-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_entry_options_alter_party_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='voting_status',
            field=models.CharField(choices=[('U', 'Upcoming'), ('L', 'Live'), ('O', 'Voting open'), ('C', 'Voting closed')], default='U', max_length=1),
        ),
    ]
