# Generated by Django 5.0.6 on 2024-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_alter_entry_compo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
