# Generated by Django 5.0.6 on 2024-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_entry_contact_phone_entry_contact_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='technology',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
