# Generated by Django 5.0.6 on 2024-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_entry_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='team',
            field=models.CharField(help_text='e.g. demogroup', max_length=32),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Recommended 1920x1080 or 1280x720', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='e.g. Färjan', max_length=32),
        ),
    ]
