# Generated by Django 5.0.6 on 2024-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0011_alter_entry_team_alter_entry_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='current_entry_pos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
