# Generated by Django 5.0.6 on 2024-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0012_compo_current_entry_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compo',
            name='voting_status',
            field=models.CharField(choices=[('U', 'Voting will begin shortly'), ('L', 'Voting is live!'), ('O', 'Voting is open!'), ('C', 'Voting is closed.')], default='U', max_length=1),
        ),
    ]
