# Generated by Django 5.0.6 on 2024-06-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0013_alter_compo_voting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
    ]
