# Generated by Django 5.0.6 on 2024-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0014_remove_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compo',
            name='voting_status',
            field=models.CharField(choices=[('U', 'Voting is not yet open.'), ('L', 'Voting is live.'), ('O', 'Voting is open.'), ('C', 'Voting has ended.')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one party can be active at a time. Users are redirected to active party after login'),
        ),
    ]
