# Generated by Django 5.0.6 on 2024-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0015_alter_compo_voting_status_alter_party_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='team_member_count',
            field=models.PositiveIntegerField(default=1, help_text='How many of you are there in your team?'),
        ),
    ]
