# Generated by Django 5.0.6 on 2024-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0018_alter_entry_sub_file_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended 1920x1080 or 1280x720', upload_to='thumbnails/'),
        ),
    ]
