# Generated by Django 5.0.6 on 2024-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0019_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Will be used as the thumbnail for the Youtube upload after the event', upload_to='thumbnails/'),
        ),
    ]
