# Generated by Django 5.0.6 on 2024-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0020_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='team_member_count',
            new_name='team_size',
        ),
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Used in voting and YouTube. Will be resized to 1280 × 720.', upload_to='thumbnails/'),
        ),
    ]
