# Generated by Django 5.0.6 on 2024-06-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0020_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contact_telegram',
        ),
    ]
