# Generated by Django 5.0.6 on 2024-06-08 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0021_remove_entry_contact_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sub_file',
            field=models.FileField(blank=True, upload_to='entries/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
