# Generated by Django 5.0.6 on 2024-06-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0021_rename_team_member_count_entry_team_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contact_telegram',
        ),
    ]
