# Generated by Django 5.0.6 on 2024-05-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_entry_options_alter_party_options'),
        ('vote', '0002_alter_votekey_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.entry')),
                ('votekey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.votekey')),
            ],
            options={
                'unique_together': {('entry', 'votekey')},
            },
        ),
    ]
