# Generated by Django 5.0.6 on 2024-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_vote_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='points',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
