# Generated by Django 5.0.6 on 2024-06-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0022_alter_entry_sub_file'),
        ('vote', '0005_alter_vote_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='party.entry'),
        ),
    ]
